#!/bin/bash


_python_() {
    python3${pVer%.*} -c "$1"
}

_DOMINATORBOT_MAIN() {
    $(_python_ 'from git import Repo
import sys
_UPSTREAM_ = "https://github.com/dominator454/DOMINATORXBOT"
_BRANCH_ = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", _UPSTREAM_)
origin.fetch()
repo.create_head(_BRANCH_, origin.refs[_BRANCH_])
repo.heads[_BRANCH_].checkout(True) ')
}

_dominator_repo () {
    local hrepo
    hrepo=`echo "aHR0cHM6Ly9naXRodWIuY29tL2RvbWluYXRvcjQ1NC9ET01JTkFUT1JYVVNFUkJPVA==" | base64 -d`
    echo "$rlink"
}

_dominator_zip () {
    echo "aHR0cHM6Ly9naXRodWIuY29tL2RvbWluYXRvcjQ1NC9ET01JTkFUT1JYVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
}

_DOMINATORBOT_PLUG() {
    local hrepo=$(_dominator_repo)
    $(_python_ 'from git import Repo
import sys
_UPSTREAM_ = "'$hrepo'"
_BRANCH_ = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", _UPSTREAM_)
origin.fetch()
repo.create_head(_BRANCH_, origin.refs[_BRANCH_])
repo.heads[_BRANCH_].checkout(True) ')
}

_starter () {
    local dominatorpath
    dominatorpath="DOMINATORXSERBOT.zip"
    echo "╔════❰𓆩༒𝕾𝖙𝖆𝖗𝖙𝖎𝖓𝖌𓆩༒❱═❍⊱❁"
    echo "║╭━━━━━━━━━━━━━━━➣"
    echo "║┣⪼𓆩༒  𝖀𝖑𝖙𝖗𝖆 𝕻𝖔𝖜𝖊𝖗𝕱𝖚𝖑𝖑༒𓆪"
    echo "║┣⪼𓆩༒𝕺𝖜𝖓𝖊𝖗 𝕺𝖋 ༒𓆪"
    echo "║╰━━━━━━━━━━━━━━━➣"
    echo "╚══════════════════❍⊱❁۪۪"
    wget -q $(_dominator_zip) -O "$dominatorpath"
    DOMINATORPATH=$(zipinfo -1 "$dominatorpath" | grep -v "/.");
    unzip -qq "$dominatorpath"
    rm -rf "$dominatorpath"
    # _DOMINATORBOT_MAIN
    cd $DOMINATORPATH
    # _DOMINATORBOT_PLUG
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    echo "╭━━━━━━━━━━━━━━━➣"
    echo "║┣⪼𝕷𝖔𝖆𝖉𝖎𝖓𝖌.  𝕻𝖔𝖜𝖊𝖗𝕱𝖚𝖑𝖑 𝕽𝖔𝕭𝖔𝖔𝖙"
    echo "╰━━━━━━━━━━━━━━━➣"
    python3 -m DominatorBot
}

_starter
